import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sistem Pengelolaan Limbah</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={styles.main}>
        <ConnectButton />
        <h1 className={styles.title}>Selamat Datang di Sistem Pengelolaan Limbah</h1>
        <form className={styles.form}>
          <label>Nama Limbah : </label>
          <input type="text" placeholder="Masukkan Nama Limbah"/>
          <label>Jenis Limbah : </label>
          <input type="text" placeholder="Masukkan Jenis Limbah"/>
          <label>Berat Limbah : </label>
          <input type="text" placeholder="Masukkan Berat Limbah "/>
          <label>Sumber Limbah : </label>
          <input type="text" placeholder="Masukkan Sumber Limbah"/>
          <label>Jumlah Limbah : </label>
          <input type="text" placeholder="Masukkan Jumlah Limbah"/>
          <label>Biaya Pengelolaan Limbah : </label>
          <input type="text" placeholder="Masukkan Biaya"/>
          <label>Pihak Penyalur Limbah : </label>
          <input type="text" placeholder="Masukkan Pihak"/>
          <button type="submit">Submit</button>
        </form>
        <div>
          <h1>Cari Limbah </h1>
          <label>ID Limbah : </label>
          <input type="text" placeholder="Masukkan ID"/>
          
        </div>
      </main>
      {/* <footer className={styles.footer}>
        <p>Made with ❤️</p>
      </footer> */}
    </div>
  );
};

export default Home;
